### ISSUE TITLE
Getting compilation error 

### ISSUE THREAD

**Issue by hiteshpanchani** [EIPStackGroup/OpENerFileObject#1]
In file included from /opt/OpENer-master/source/src/cip/cipassembly.c:13:0:
/opt/OpENer-master/source/src/opener_api.h:237:6: note: expected ‘CipAttributeEncodeInMessage {aka void (*)(const void * const,  struct enip_message * const)}’ but argument is of type ‘void (*)(const CipUint * const,  ENIPMessage * const) {aka void (*)(const short unsigned int * const,  struct enip_message * const)}’
 void InsertAttribute(CipInstance *const instance,
      ^
[ 27%] Building C object src/cip/CMakeFiles/CIP.dir/cipclass3connection.c.o
[ 30%] Building C object src/cip/CMakeFiles/CIP.dir/cipcommon.c.o
/opt/OpENer-master/source/src/cip/cipcommon.c:31:59: fatal error: CIPElectricalEnergyObject/cipelectricalenergy.h: No such file or directory
compilation terminated.
src/cip/CMakeFiles/CIP.dir/build.make:134: recipe for target 'src/cip/CMakeFiles/CIP.dir/cipcommon.c.o' failed
make[2]: *** [src/cip/CMakeFiles/CIP.dir/cipcommon.c.o] Error 1
CMakeFiles/Makefile2:202: recipe for target 'src/cip/CMakeFiles/CIP.dir/all' failed

**Comment by hiteshpanchani** [comment]
I am using headless Ubuntu 16.x for to setup OpENer.

**Comment by hiteshpanchani** [comment]
Is there any way we can add this cip module without cmake gui utility?

**Comment by CapXilinx** [comment]
Hi,

your compilation error comes from a not resolvable include "CIPElectricalEnergyObject/cipelectricalenergy.h", which I cannot find in the current source of OpENer.

You can either use cmake directly and activate the appropriate switch or you can use the cmake-curses-gui, which is a terminal gui.

**Comment by CapXilinx** [comment]
Closed due to inactivity
