### ISSUE TITLE
Configure CMakeLists without gui

### ISSUE THREAD

**Issue by wgthompson** [EIPStackGroup/OpENerFileObject#4]
Hello,
I am trying to do this all from terminal. How can you configure sans using the cmake ui?

I have tried moving cipfile.c/h over to source/src/ports/POSIX but am still getting errors when attempting to run. Specifically  `Assertion kEipstatusOk == eip_status failed` when attempting to run. 
Thanks

**Comment by CapXilinx** [comment]
Moving the files alone does not help here.
The easiest way to do it from the terminal is to use the textual user interface for cmake called ccmake.
